const express = require('express');
const { getResources, createResource, toggleLike, deleteResource } = require('../controllers/resourceController');
const { protect } = require('../middleware/auth');
const { cache } = require('../middleware/cache');
const { uploadResource } = require('../config/cloudinary');
const router = express.Router();
router.use(protect);
router.get('/', cache('resources'), getResources);
router.post('/', uploadResource.single('file'), createResource);
router.post('/:id/like', toggleLike);
router.delete('/:id', deleteResource);
module.exports = router;